- name: KUBE MASTER INSTALL
  connection: network_cli
  gather_facts: false
  hosts: 127.0.0.1
  become: true
  connection: local

  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
  - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
    shell: |
      swapoff -a
  - name: install openssh server
    apt:
      pkg:
      - openssh-server
      - docker.io
      - apt-transport-https
      - curl

  - name: Add an Apt signing key, uses whichever key is at the URL
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Add a line to a file if the file does not exist, without passing regexp
    lineinfile:
      destfile: /etc/apt/sources.list.d/kubernetes.list
      line: deb http://apt.kubernetes.io/ kubernetes-xenial main
      create: yes
      state: present
  - name: Run the equivalent of "apt-get update"
    apt:
      update_cache: yes

  - name: install kube
    apt:
      pkg:
      - kubelet
      - kubeadm
      - kubectl

  - name: kubeadm update
    lineinfile:
      destfile: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
      line: Environment="cgroup-driver=systemd/cgroup-driver=cgroupfs"
      create: yes
      state: present

  - name: kubeinit
    command: kubeadm init --apiserver-advertise-address=hostvars[inventory_hostname]['ansible_default_ipv4']['address'] --pod-network-cidr=192.168.0.0/16 

  - name: create .kube
    command: mkdir -p $HOME/.kube;cp -i /etc/kubernetes/admin.conf $HOME/.kube/config; chown $(id -u):$(id -g) $HOME/.kube/config

  - name: kubectl apply calio
    command: kubectl apply -f  https://docs.projectcalico.org/v3.8/manifests/calico.yaml
